In [1]:
import numpy as np
import matplotlib.pyplot as plt
from nn import io, nn, preprocess
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

In [2]:
%load_ext autoreload
%autoreload 2

In [35]:
digits = load_digits()
print("digit data: ", digits['data'])

digit data:  [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
digit data shape:  (1797, 64)


In [40]:
X_train, X_test, y_train, y_test = train_test_split(digits['data'], digits['target'], test_size=0.2, random_state=0)
print("train shape: ", X_train.shape)
print("test shape: ", X_test.shape)

train shape:  (1437, 64)
test shape:  (360, 64)


In [41]:
nn_arch = [{'input_dim': 64, 'output_dim': 16, 'activation': 'relu'}, {'input_dim': 16, 'output_dim': 64, 'activation:': 'relu'}]
lrs = np.logspace(-1.0, -5.0, num=5)
seed = 42
batch_sizes = np.linspace(10, 150, 8)
epochss = np.linspace(50, 500, 10)
loss_function = 'mse'
hyperparams = {}

for lr in lrs:
    for batch_size in batch_sizes:
        for epochs in epochss:
            
            autoencoder = nn.NeuralNetwork(nn_arch=nn_arch, lr=lr, seed=seed, batch_size=batch_size, epochs=epochs, loss_function=loss_function)
            _, loss_test = autoencoder.fit(X_train, y_train, X_test, y_test)
            hyperparams[('lr=' + str(lr), 'batch size=' + str(batch_size), 'epochs=' + str(epochs))] = loss_test[-1]

print("optimal hyperparameters for training are: ", min(hyperparams, key=hyperparams.get))


TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [11]:
nn_arch = [{'input_dim': 8, 'output_dim': 4, 'activation': 'relu'}, {'input_dim': 4, 'output_dim': 2, 'activation:': 'sigmoid'}]
lr = 0.1
seed = 42
batch_size = 10
epochs = 100
loss_function_mse = 'mse' 
loss_function_bce = 'bce'

nn_test = nn.NeuralNetwork(nn_arch=nn_arch, lr=lr, seed=seed, batch_size=batch_size, epochs=epochs, loss_function=loss_function_mse)

In [22]:
nn_test._param_dict['b2']

array([[-0.1478522 ],
       [-0.07198442]])

In [23]:
a, z = nn_test._single_forward(nn_test._param_dict['W2'], nn_test._param_dict['b2'], np.random.randint(2, size=len(nn_test._param_dict['W1'])), nn_arch[0]['activation'])


In [24]:
a

array([[-0., -0.]])

In [25]:
z

array([[-0.1478522 , -0.07198442]])